IF DEF(_GREEN)
STARTER1 EQU KANGASKHAN
STARTER2 EQU NIDORAN_M
STARTER3 EQU CLEFAIRY

ELIF DEF(_RED)
STARTER1 EQU SNORLAX
STARTER2 EQU DRATINI
STARTER3 EQU PIKACHU

ELIF DEF(_BLUE)
STARTER1 EQU PIDGEY
STARTER2 EQU SQUIRTLE
STARTER3 EQU GASTLY

ELSE
STARTER1 EQU CHARMANDER
STARTER2 EQU SQUIRTLE
STARTER3 EQU BULBASAUR

ENDC
