IF DEF(_RADZ)
STARTER1 EQU RATTATA
STARTER2 EQU MAGIKARP
STARTER3 EQU PIDGEY
R_STARTER1 EQU PIDGEY
R_STARTER2 EQU SQUIRTLE
R_STARTER3 EQU GASTLY

ELIF DEF(_LNKN)
STARTER1 EQU SNORLAX
STARTER2 EQU DRATINI
STARTER3 EQU PIKACHU
R_STARTER1 EQU RATTATA
R_STARTER2 EQU MAGIKARP
R_STARTER3 EQU PIDGEY

ELIF DEF(_GLAU)
STARTER1 EQU PIDGEY
STARTER2 EQU SQUIRTLE
STARTER3 EQU GASTLY
R_STARTER1 EQU SNORLAX
R_STARTER2 EQU DRATINI
R_STARTER3 EQU PIKACHU

ELSE
STARTER1 EQU CHARMANDER
STARTER2 EQU SQUIRTLE
STARTER3 EQU BULBASAUR
R_STARTER1 EQU STARTER2
R_STARTER2 EQU STARTER3
R_STARTER3 EQU STARTER1

ENDC
